/**
 * The arena's share card.
 *
 * This intentionally goes through `ratingBoard()` and `arenaFeed()` rather
 * than looking up users or events itself. A card is a public surface just as
 * much as the board and feed are: anonymous competitors must remain
 * pseudonymous, and a hidden member must not be recoverable from a preview
 * generated by an unfurled link.
 */

import { ImageResponse } from "next/og";
import { arenaFeed, formatDuration, getDb, ratingBoard } from "@usurp/db";

export const alt = "Usurp arena standings";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";
// The card reads the Postgres-backed board and feed, so it cannot run in the
// edge runtime that `ImageResponse` examples commonly use for static copy.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function points(value: number): string {
  return value.toLocaleString();
}

/** Shared by the global and per-arena metadata routes. */
export async function renderArenaCard(slug: string) {
  const [board, feed] = await Promise.all([
    ratingBoard(getDb(), slug, { limit: 3 }),
    arenaFeed(getDb(), slug, { limit: 1 }),
  ]);

  if (!board) {
    return new ImageResponse(
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#0b0d10",
          color: "#e7eaee",
          fontSize: 54,
          fontWeight: 700,
        }}
      >
        Usurp.
      </div>,
      size,
    );
  }

  // `throne.display` was resolved by `ratingBoard()` under the arena's
  // visibility rules. Do not infer it from the first visible row: a hidden
  // Sovereign is absent from that list, and calling their challenger the
  // holder would be both wrong and a privacy footgun.
  const leaderName = board.throne?.display ?? "Someone";
  const headline = board.throne
    ? `${leaderName} holds the Throne`
    : "The Throne is waiting";
  const detail = board.throne
    ? `Sovereign for ${formatDuration(board.throne.heldSeconds)}`
    : "Be the first Sovereign this season.";
  const feedLine = feed?.entries[0]?.text;

  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        padding: "58px 66px",
        background: "#0b0d10",
        color: "#e7eaee",
        fontFamily: "sans-serif",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", color: "#d8a657", fontSize: 30, fontWeight: 700 }}>
        Usurp.
        <span style={{ marginLeft: 22, color: "#8b95a3", fontSize: 22, fontWeight: 500 }}>
          {board.arena.name}
        </span>
      </div>

      <div style={{ display: "flex", flexDirection: "column", marginTop: 62 }}>
        <span style={{ color: "#8b95a3", fontSize: 22, letterSpacing: 2 }}>SEASON {board.season.idx}</span>
        <span style={{ marginTop: 12, fontSize: 62, fontWeight: 700, letterSpacing: -2 }}>{headline}</span>
        <span style={{ marginTop: 12, color: "#d8a657", fontSize: 28 }}>{detail}</span>
      </div>

      <div style={{ display: "flex", gap: 18, marginTop: 54 }}>
        {board.rows.slice(0, 3).map((row) => (
          <div
            key={row.userId}
            style={{
              display: "flex",
              flexDirection: "column",
              width: 300,
              padding: "18px 20px",
              border: "1px solid #232830",
              borderRadius: 10,
              background: row.title === "sovereign" ? "#1a1710" : "#12151a",
            }}
          >
            <span style={{ color: "#8b95a3", fontSize: 18 }}>#{row.rank} {row.title?.toUpperCase() ?? ""}</span>
            <span style={{ marginTop: 8, fontSize: 26, fontWeight: 600 }}>
              {row.handle ?? row.pseudonym ?? "Anonymous"}
            </span>
            <span style={{ marginTop: 8, color: "#d8a657", fontSize: 22 }}>{points(row.points)} pts</span>
          </div>
        ))}
      </div>

      {feedLine && (
        <div style={{ display: "flex", marginTop: "auto", color: "#8b95a3", fontSize: 20 }}>
          {feedLine}
        </div>
      )}
    </div>,
    size,
  );
}

export default async function OpenGraphImage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  return renderArenaCard((await params).slug);
}
