import { afterEach, expect, it } from "vitest";
import { DatabaseSync } from "node:sqlite";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CursorReader, cursorModel } from "./cursor.js";
const dirs: string[] = [];
afterEach(async () => { for (const d of dirs.splice(0)) await rm(d, { recursive: true }); });
it("reads actual IDE GPT selections and never invents billing from metadata", async () => {
  const dir = await mkdtemp(join(tmpdir(), "usurp-cursor-")); dirs.push(dir);
  const file = join(dir, "state.vscdb"); const db = new DatabaseSync(file);
  db.exec("CREATE TABLE cursorDiskKV (key TEXT PRIMARY KEY, value TEXT)");
  const add = db.prepare("INSERT INTO cursorDiskKV VALUES (?, ?)");
  add.run("composerData:1", JSON.stringify({ createdAt: Date.parse("2026-09-08T10:00:00Z"), fullConversationHeadersOnly: [{ bubbleId: "a", type: 1 }], modelConfig: { modelName: "gpt-5.6-sol-medium" }, blobEncryptionKey: "never transmit", text: "private" }));
  add.run("composerData:draft", JSON.stringify({ createdAt: Date.now(), fullConversationHeadersOnly: [] }));
  add.run("bubbleId:1:measured", JSON.stringify({ type: 2, tokenCount: { inputTokens: 100, outputTokens: 20 }, createdAt: "2026-09-08T10:01:00Z", modelInfo: { modelName: "gpt-5.6-terra" } }));
  add.run("bubbleId:1:placeholder", JSON.stringify({ type: 2, tokenCount: { inputTokens: 0, outputTokens: 0 }, createdAt: "2026-09-08T10:02:00Z" }));
  add.run("bubbleId:1:undated", JSON.stringify({ type: 2, tokenCount: { inputTokens: 400, outputTokens: 50 } }));
  db.close();
  const reader = new CursorReader(file); expect(await reader.detect()).toBe(true);
  const result = await reader.read(); expect(result.sessions).toHaveLength(1);
  expect(result.sessions[0]).toMatchObject({ agent: "cursor", startModel: "gpt-5.6-sol", outcome: "in_progress" });
  expect(result.calls).toHaveLength(1);
  expect(result.calls[0]).toMatchObject({ model: "gpt-5.6-terra", inputTokens: 100, outputTokens: 20 });
  expect(JSON.stringify(result)).not.toContain("private");
  expect(result.warnings[0]).toContain("unavailable");
  expect(cursorModel("inherit")).toBe("cursor-auto-unknown");
  expect((await reader.read({ since: new Date("2026-09-09") })).sessions).toEqual([]);
});
